---
- name: Resize disk and file system
  hosts: first
  become: yes
  remote_user: azureadmin
  vars:
    new_disk: "/dev/sdc"
    vg_name: "my_azure_vg"
    lv_name: "my_azure_lv"
    mount_point: "/first_fs"
    ansible_user: azureadmin
    ansible_ssh_private_key_file: /opt/git/azure_id_rsa

  tasks:
    - name: Resize partition on the disk
      ansible.builtin.parted:
        device: "{{ new_disk }}"
        number: 1
        part_end: "100%"
        resize: true
        state: present

    - name: Resize physical volume
      command: pvresize "{{ new_disk }}1"

    - name: Resize logical volume
      lvol:
        vg: "{{ vg_name }}"
        lv: "{{ lv_name }}"
        size: +100%FREE

    - name: Resize XFS filesystem
      command: xfs_growfs "{{ mount_point }}"

